# Use the .NET SDK image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Set the working directory to Client
WORKDIR /code/Client

# Copy the entire client directory into the container
COPY ./GrpcClient/ .

# Restore dependencies and build the project
RUN dotnet restore
RUN dotnet build