# Devam Punitbhai Patel

version: '3.9'
services:
  grpc-server:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: grpc-server
    working_dir: "/code/GrpcServer"
    volumes:
      - ./GrpcServer:/code
    command: dotnet run
    stdin_open: true
    tty: true
  grpc-client:
    depends_on:
      - grpc-server
    build: 
      context: ./Client
      dockerfile: Dockerfile-client
    container_name: grpc-client
    environment:  # setup the base url as environment variable
      - BASE_URL=http://grpc-server:5063
    working_dir: "/code/Client"
    command: dotnet run
    stdin_open: true
    tty: true